create table tbl_produto (id_produto integer generated by default as identity, descricao varchar(255) not null, preco float(53) not null, primary key (id_produto));
insert into tbl_produto(descricao, preco) values ('Computador', 1500.0);
insert into tbl_produto(descricao, preco) values ('Mouse', 50.0);
insert into tbl_produto(descricao, preco) values ('Teclado', 100.0);
insert into tbl_produto(descricao, preco) values ('Monitor', 500.0);
